def parse_server_info(file_content):
    """
    Parse ServerInfo.txt generated by the Windows batch file.

    Returns:
        {
            "hostname": str | None,
            "execution_time": str | None,
            "ip_addresses": list[str]
        }
    """

    server_info = {
        "hostname": None,
        "execution_time": None,
        "ip_addresses": []
    }

    reading_ip_addresses = False

    for raw_line in file_content.splitlines():
        line = raw_line.strip()

        if not line:
            continue

        if line.startswith("Hostname:"):
            server_info["hostname"] = line.split(":", 1)[1].strip()
            reading_ip_addresses = False
            continue

        if line.startswith("Execution Time:"):
            server_info["execution_time"] = line.split(":", 1)[1].strip()
            reading_ip_addresses = False
            continue

        if line.startswith("IPv4 Address"):
            reading_ip_addresses = True
            continue

        if reading_ip_addresses:
            # Accept IPv4-looking values such as 10.5.0.5.
            parts = line.split(".")

            if len(parts) == 4 and all(
                part.isdigit() and 0 <= int(part) <= 255
                for part in parts
            ):
                server_info["ip_addresses"].append(line)
            else:
                reading_ip_addresses = False

    return server_info